CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
CREATE ROLE IF NOT EXISTS AIRFLOW_ROLE;

CREATE USER IF NOT EXISTS AIRFLOW_USER
  LOGIN_NAME = 'AIRFLOW_USER'
  DISPLAY_NAME = 'Airflow Pipeline User'
  DEFAULT_ROLE = AIRFLOW_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE DATABASE AIRFLOW_DATA;  
USE DATABASE AIRFLOW_DATA;
CREATE SCHEMA airflow;

-- CREATE AN EXTERNAL STAGE OF AWS --
-- ADD YOUR STAGE NAME ( STOCKS_STAGE )
-- ADD YOUR S3 URL 
-- GO TO CREDENTIALS 
-- PASS YOUR ACCESS KEY AND SECRET KEY

CREATE OR REPLACE TABLE STOCK_DATA (
    DATE DATE,
    SYMBOL STRING,
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    ADJ_CLOSE FLOAT,
    VOLUME FLOAT,
    CLOSE_CHANGE FLOAT,
    CLOSE_PCT_CHANGE FLOAT,
    DAILY_RANGE FLOAT,
    DAILY_RANGE_PCT FLOAT
);


GRANT ROLE AIRFLOW_ROLE TO USER AIRFLOW_USER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON DATABASE AIRFLOW_DATA TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA AIRFLOW_DATA.airflow TO ROLE AIRFLOW_ROLE;

-- For the target table
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE AIRFLOW_DATA.airflow.STOCK_DATA TO ROLE AIRFLOW_ROLE;

-- If using an external stage for S3
GRANT USAGE ON STAGE AIRFLOW_DATA.airflow.STOCKS_STAGE TO ROLE AIRFLOW_ROLE;

ALTER USER AIRFLOW_USER SET PASSWORD = 'airflow';

SHOW USERS LIKE 'AIRFLOW_USER';

SELECT * FROM STOCK_DATA

